### ISSUE TITLE
Feature: Application.yml should include properties related to custom solution  exporters. 

### ISSUE THREAD

**Issue by scaverod** [rmartinsanta/mork#44]
For example: 

```
serializers:
  solution-common:
    # Path where solutions will be exported (Only if a solution serializer is enabled, see below)
    folder: 'solutions'
   [...]
    custom:
    # Export your solutions.  One, and only one class (I suppose ❓ ) must extend SolutionSerializer
    enabled: false
```
